name: CI CD Deploy Website via Local Agent

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    # Chỉ định chạy trên Agent local của bạn
    runs-on: self-hosted

    steps:
      # BƯỚC 1: Agent tự động pull mã nguồn mới nhất từ GitHub về thư mục riêng của nó
      - name: Agent Pull Code Từ GitHub
        uses: actions/checkout@v4

      # BƯỚC 3: Agent chạy lệnh đẩy file index.html lên S3 Bucket
      - name: Day file len S3 Bucket
        run: |
          aws s3 cp index.html s3://bucketdemowebapp/index.html

      # BƯỚC 4: Clear cache CloudFront (Nếu cần)
      - name: Clear Cache CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E2VEV5F912D9E4 --paths "/*"